# Generated by Django 3.2.21 on 2024-04-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('lstate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(blank=True, max_length=200, null=True)),
                ('lname', models.CharField(blank=True, max_length=200, null=True)),
                ('dsalary', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jname', models.CharField(max_length=300)),
                ('jnumber', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('salary', models.CharField(blank=True, max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=300)),
                ('company_description', models.CharField(blank=True, max_length=100)),
                ('buynow', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=200)),
                ('sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True, null=True)),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('salary', models.CharField(blank=True, max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=300)),
                ('company_description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='/user.png', null=True, upload_to='images')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
