# Generated by Django 3.2.21 on 2024-06-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='balance',
        ),
    ]
