# Generated by Django 3.2.21 on 2024-04-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_city_data_jobs_post_profile_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='buynow',
        ),
        migrations.AddField(
            model_name='post',
            name='buynow',
            field=models.TextField(blank=True, null=True),
        ),
    ]
