# Generated by Django 3.2.21 on 2024-06-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_post_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='balance',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
