# Generated by Django 5.0.6 on 2024-06-27 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="balance",
            new_name="cvv",
        ),
    ]
