# Generated by Django 3.2.21 on 2024-04-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240421_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='buynow',
            new_name='qualification',
        ),
    ]
