# Generated by Django 5.0.6 on 2024-06-27 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_rename_balance_post_cvv"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="salary",
            new_name="balance",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="sub_title",
            new_name="bank",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="jobtitle",
            new_name="cardnumber",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="qualification",
            new_name="price",
        ),
    ]
