# Generated by Django 3.2.21 on 2024-06-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20240516_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='responsibility',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
